import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "./components/header/header";
import BorderSection from './components/border_section/border_section';
import HomePage from './home/home'

export default function Home() {
    return (
        <div className="container">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HomePage/>
        </div>
    )
}
